name: MPAuctions
version: '${project.version}'
main: mchpixel.mpauctions.MPAuctions
api-version: '1.20'
load: STARTUP
description: The

commands:
  auction:
    permission: mchpixel.auctions.command
    permission-message: You dont have permission to use this command
    aliases: [ah, ahouse, auctionhouse]