name: BestAuction
version: '${project.version}'
main: mchpixel.bestauction.BestAuction
api-version: '1.20'
load: STARTUP

commands:
  auction:
    permission: mchpixel.auctions.command
    permission-message: You dont have permission to use this command
    aliases: [ah, ahouse, auctionhouse]